name: Unit Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install rustup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.61.0
      - name: Install java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Install womtool
        run: |
          apt-get -y --no-install-recommends install wget;
          wget -P /usr/local/bin/womtool https://github.com/broadinstitute/cromwell/releases/download/54/womtool-54.jar;
      - name: Setup postgres db
        run: |
          PGPASSWORD=postgres psql -v ON_ERROR_STOP=1 --username "postgres" -c 'create database test_framework_db;';
          PGPASSWORD=postgres psql -v ON_ERROR_STOP=1 --username "postgres" -c "create user test_framework_user with password 'test';";
          PGPASSWORD=postgres psql -v ON_ERROR_STOP=1 --username "postgres" -c 'create extension if not exists "uuid-ossp";' test_framework_db;
      - name: Run tests with cargo
        uses: actions-rs/cargo
        with:
          command: test
          args: -- --test-threads=1
